#define MOTOR_FRONT_LEFT 1
#define MOTOR_FRONT_RIGHT 2
#define MOTOR_BACK_LEFT 3
#define MOTOR_BACK_RIGHT 4
#define MOTOR_INTAKE 5
#define MOTOR_BELT 6
#define MOTOR_FLYWHEEL_A 7
#define MOTOR_FLYWHEEL_B 9
